// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:a64e79f9-5fe6-4c18-aaae-1e773ca67d79",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_mW9cXBpcb",
    "aws_user_pools_web_client_id": "5p3tj9e4947hu8klmdq6rm9nlq",
    "oauth": {}
};


export default awsmobile;
